site_name: Wiki Modding LYCANS
site_description: 'Ce wiki contiens des informations et des resources pour aider à modder LYCANS.'
site_author: 'LYCANS MODDING Community'
site_url: 'https://lycans-modding.github.io/LMWiki/'
docs_dir: docs/
plugins:
  - search
  - ezlinks
  - mkdocs-video
  - mkdocs-fix-github-wiki-url-plugin
  - admonition
  - pymdownx.details
  - pymdownx.superfences
repo_name: 'lycans-modding/LMWiki'
repo_url: 'https://github.com/lycans-modding/LMWiki/wiki'
theme:
  name: 'material'
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
